version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: excite_ui
    ports:
      - "8080:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
